# Generated by Django 3.0.8 on 2020-07-16 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('create', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'RFID',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('rol', models.CharField(max_length=50)),
                ('create', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=50)),
                ('create', models.DateField(default=django.utils.timezone.now)),
                ('id_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RFID')),
            ],
            options={
                'db_table': 'Temperatura',
            },
        ),
        migrations.AddField(
            model_name='rfid',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
